FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/uploads

CMD ["sh", "-c", "alembic upgrade head && python -m app.seed.run_seed && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]