import os
import pandas as pd
import requests
import streamlit as st

BACKEND_URL = os.environ.get('BACKEND_URL', 'http://backend:8000')

st.set_page_config(page_title='Journal', layout='wide')
st.title('Journal Entries')
st.caption('Double-entry journal entries generated by the classification agent.')

@st.cache_data(ttl=3)
def fetch_entries():
    return requests.get(f'{BACKEND_URL}/journal-entries', timeout=10).json()

if st.button('Refresh'):
    st.cache_data.clear()

try:
    entries = fetch_entries()
except Exception as e:
    st.error(f'Could not reach backend: {e}')
    st.stop()

if not entries:
    st.info('No journal entries yet. Process an invoice first.')
    st.stop()

posted = sum(1 for e in entries if e['status'] == 'POSTED')
draft = sum(1 for e in entries if e['status'] == 'DRAFT')
total_posted = sum(float(e['total_debit']) for e in entries if e['status'] == 'POSTED')

m = st.columns(3)
m[0].metric('Posted entries', posted)
m[1].metric('Draft (awaiting reviews)', draft)
m[2].metric('Total posted value', f"{total_posted:,.2f}")

st.divider()

for e in entries:
    header = f"{e['entry_date']} - {e['description']} ({e['status']})"
    with st.expander(header):
        rows = []
        for ln in e['lines']:
            debit = float(ln['debit_amount'])
            credit = float(ln['credit_amount'])
            rows.append({
                'Account': f"{ln['account_code']} - {ln['account_name']}",
                'Debit': f"{debit:,.2f}" if debit > 0 else '',
                'Credit': f"{credit:,.2f}" if credit > 0 else '',
                'Memo': ln.get('description') or '',
            })
        st.dataframe(pd.DataFrame(rows), width=True, hide_index=True)
        balanced = abs(float(e['total_debit']) - float(e['total_credit'])) <= 0.01
        st.caption(
            f"Total debit: {float(e['total_debit']):,.2f} - "
            f"Total credit: {float(e['total_credit']):,.2f} - "
            + ('balanced' if balanced else 'not balanced')
        )