import os
import pandas as pd
import requests
import streamlit as st
from ui_helpers import JE_STATUS_BADGE, format_money, format_date

BACKEND_URL = os.environ.get('BACKEND_URL', 'http://backend:8000')

st.set_page_config(page_title='Journal', layout='wide')
st.title('Journal Entries')
st.caption('Double-entry journal entries generated by the classification agent.')

@st.cache_data(ttl=3)
def fetch_entries():
    return requests.get(f'{BACKEND_URL}/journal-entries', timeout=10).json()

@st.cache_data(ttl=5)
def fetch_export_csv() -> bytes:
    return requests.get(f'{BACKEND_URL}/journal-entries/export', timeout=15).content

ENTRY_TYPE_BADGE = {'BILL': 'Bill', 'PAYMENT': 'Payment'}

top = st.columns([1, 1, 5])
if top[0].button('Refresh'):
    st.cache_data.clear()

try:
    entries = fetch_entries()
except Exception as e:
    st.error(f'Could not reach backend: {e}')
    st.stop()

if not entries:
    st.info('No journal entries yet. Process an invoice first.')
    st.stop()

try:
    csv_bytes = fetch_export_csv()
    top[1].download_button('Export CSV', data=csv_bytes, file_name='journal_entries.csv', mime='text/csv')
except Exception as e:
    top[1].caption(f'Export unavailable: {e}')

# Summary metrics
bills = [e for e in entries if e.get('entry_type', 'BILL') == 'BILL']
payments = [e for e in entries if e.get('entry_type') == 'PAYMENT']
posted = [e for e in entries if e['status'] == 'POSTED']
draft = [e for e in entries if e['status'] == 'DRAFT']
total_posted = sum(float(e['total_debit']) for e in posted)

m = st.columns(5)
m[0].metric('Total entries', len(entries))
m[1].metric('Bills', len(bills))
m[2].metric('Payments recorded', len(payments))
m[3].metric('Draft (awaiting reviews)', draft)
m[4].metric('Total posted value', format_money(total_posted))

# Filters
filter_cols = st.columns(2)
all_statuses = sorted({e['status'] for e in entries})
selected_statuses = filter_cols[0].multiselect('Filter by status', all_statuses, default=all_statuses)
all_types = sorted({e.get('entry_type', 'BILL') for e in entries})
selected_types = filter_cols[1].multiselect('Filter by type', all_types, default=all_types, format_func=lambda t: ENTRY_TYPE_BADGE.get(t, t))
filtered = [e for e in entries if e['status'] in selected_statuses and e.get('entry_type', 'BILL') in selected_types]

st.divider()

# Entries
for e in filtered:
    badge = JE_STATUS_BADGE.get(e['status'], e['status'])
    type_badge = ENTRY_TYPE_BADGE.get(e.get('entry_type', 'BILL'), '')
    header = (
        f"{type_badge}  {badge} {format_date(e['entry_date'])}  "
        f"{e['description']}  ·  {format_money(e['total_debit'])}"
    )
    with st.expander(header):
        rows = []
        for ln in e['lines']:
            debit = float(ln['debit_amount'])
            credit = float(ln['credit_amount'])
            rows.append({
                'Account': f"{ln['account_code']} · {ln['account_name']}",
                'Debit': format_money(debit) if debit > 0 else '',
                'Credit': format_money(credit) if credit > 0 else '',
                'Memo': ln.get('description') or '',
            })
        st.dataframe(pd.DataFrame(rows), width='stretch', hide_index=True)
        balanced = abs(float(e['total_debit']) - float(e['total_credit'])) <= 0.01
        st.caption(
            f"Total debit {format_money(e['total_debit'])}  "
            f"total credit {format_money(e['total_credit'])}    "
            + ('balanced' if balanced else 'not balanced')
        )